name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
          cache: 'npm' # speeds up installs by caching node_modules

      - name: Install dependencies
        run: npm ci # faster and ensures package-lock.json consistency

      - name: Run tests
        run: npm test

      - name: Run coverage
        run: npm run coverage
